name: Update Website

on:
  push:
    branches:
      main
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.13.x

      - name: Install dependencies
        run: npm install 

      - name: Deploy
        run: |
          git config user.email "andriisharapatov@gmail.com"
          git config user.name "Andrii S"
          npm run deploy
        
