name: Update Website

on:
  push:
    branches:
      main
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.13.x

      - name: Install dependencies
        run: npm install 

      - name: Build
        run:
          git config --global user.email "andriisharapatov@gmail.com"
          git config --global user.name "Andrii S"

      - name: Deploy
        run: npm run deploy
